=== DataGeek404/sound-picture/electron-app/src/template-schema-1.0.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"version": {
			"title": "Template Version",
			"type": "string",
			"pattern": "^\\d+\\.\\d+\\.\\d+$",
			"description": "A valid semver version string (https://semver.org/)"
		},
		"minBlenderVersion": {
			"title": "Minimum Blender Version",
			"type": "string",
			"pattern": "^\\d+\\.\\d+\\.\\d+$",
			"description": "A valid semver version string (https://semver.org/)"
		},
		"allowCompositionNode": {
			"title": "Allow Composition Node",
			"type": "boolean",
			"description": "Will enable/disable option to render with active composition node in SSP GUI"
		},
		"allowTransparent": {
			"title": "Allow Transparent render",
			"type": "boolean",
			"description": "Will enable/disable option to render transparent image or video in SSP GUI"
		},
		"description": {
			"title": "Description",
			"type": "string",
			"description": "Template description displayed in SSP GUI template overview"
		},
		"license": {
			"title": "License",
			"type": "string",
			"enum": [
				"public-domain",
				"by-nc-nd-3.0",
				"by-nc-sa-3.0",
				"by-nc-3.0",
				"by-nd-3.0",
				"by-sa-3.0",
				"by-3.0",
				"gpl-3",
				"all-rights-reserved"
			],
			"description": "The license of your template"
		},
		"url": {
			"title": "Url",
			"type": "string",
			"description": "A link to your social media or template website displayed in SSP GUI template overview"
		},
		"parms": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"type": {
						"title": "Type",
						"type": "string",
						"enum": [
							"text",
							"file",
							"color"
						],
						"description": "The rendered GUI input type inside SSP GUI"
					},
					"title": {
						"title": "Title",
						"type": "string",
						"description": "The Title/Name the of the use input control presented to user inside SSP GUI"
					},
					"value": {
						"type": "string",
						"title": "Default Value",
						"description": "The default value a the parameter presented to user inside SSP GUI (Useful for colors)"
					},
					"accept": {
						"title": "Accept",
						"type": "string",
						"description": "Allow to define acceptable file types for file picker control inside SSP GUI for example \"image/png, image/gif, image/jpeg\""
					},
					"path": {
						"title": "Full Data Path",
						"type": "string",
						"description": "Use \"Copy Full Data Path\" in blender and paste it here"
					}
				},
				"required": [
					"type",
					"title",
					"path",
					"value"
				]
			}
		}
	},
	"required": [
		"version",
		"minBlenderVersion",
		"allowCompositionNode",
		"allowTransparent",
		"description",
		"license",
		"parms"
	]
}

=== DataGeek404/sound-picture/electron-app/src/static/templates/@factory/breathing-tile/template.json
{
    "version": "1.0.1",
    "minBlenderVersion": "3.4.1",
    "allowCompositionNode": true,
    "allowTransparent": false,
    "description": "Breathing Tiles",
    "license": "public-domain",
    "url": "https://github.com/s-a/sonic-sound-picture",
    "parms": [
        {
            "type": "color",
            "title": "Top Color",
            "value": "#6CEEE2",
            "path": "bpy.data.materials[\"SecondaryColor\"].node_tree.nodes[\"ColorRamp\"].color_ramp.elements[1].color"
        },
        {
            "type": "color",
            "title": "Bottom Color",
            "value": "#E12D16",
            "path": "bpy.data.materials[\"PrimaryColorWithNoise\"].node_tree.nodes[\"ColorRamp\"].color_ramp.elements[0].color"
        },
        {
            "type": "color",
            "title": "Accent Color",
            "value": "#F6FE48",
            "path": "bpy.data.materials[\"AccentColor\"].node_tree.nodes[\"ColorRamp\"].color_ramp.elements[0].color"
        },
        {
            "type": "color",
            "title": "Background Color",
            "value": "#0D0D0D",
            "path": "bpy.data.worlds[\"World\"].node_tree.nodes[\"Background\"].inputs[0].default_value"
        }
    ]
}

=== DataGeek404/sound-picture/electron-app/src/static/templates/@factory/digital-water/template.json
{
	"version": "1.0.1",
	"minBlenderVersion": "3.4.1",
	"allowCompositionNode": false,
	"allowTransparent": false,
	"description": "Circly experience",
	"license": "public-domain",
	"parms": [
		{
			"type": "text",
			"title": "Band Name",
			"value": "",
			"path": "bpy.data.objects[\"Band Name\"].modifiers[\"GeometryNodes\"][\"Input_2\"]"
		},
		{
			"type": "text",
			"title": "Song Name",
			"value": "",
			"path": "bpy.data.objects[\"Song Name\"].modifiers[\"GeometryNodes\"][\"Input_2\"]"
		},
		{
			"type": "color",
			"title": "Primary Ring Color",
			"value": "#D705F2",
			"path": "bpy.data.materials[\"Material.001\"].node_tree.nodes[\"ColorRamp\"].color_ramp.elements[0].color"
		},
		{
			"type": "color",
			"title": "Secondary Ring Color",
			"value": "#220126",
			"path": "bpy.data.materials[\"Material.001\"].node_tree.nodes[\"ColorRamp\"].color_ramp.elements[1].color"
		}
	]
}

=== DataGeek404/sound-picture/electron-app/src/static/templates/@factory/wired-love/template.json
{
	"version": "1.0.1",
	"minBlenderVersion": "3.4.1",
	"allowCompositionNode": true,
	"allowTransparent": true,
	"description": "Clean and simple waveform. Due to the simplified representation, it is very well suited to be rendered transparently and then used in your own video compositions using 3rd. party software.",
	"license": "public-domain",
	"parms": [
		{
			"type": "color",
			"title": "Waveform Color Ramp - Color 1",
			"value": "#F26B9C",
			"path": "bpy.data.materials[\"Material\"].node_tree.nodes[\"WaveFormColorRamp\"].color_ramp.elements[0].color"
		},
		{
			"type": "color",
			"title": "Waveform Color Ramp - Color 2",
			"value": "#30A9D9",
			"path": "bpy.data.materials[\"Material\"].node_tree.nodes[\"WaveFormColorRamp\"].color_ramp.elements[1].color"
		},
		{
			"type": "color",
			"title": "Waveform Color Ramp - Color 3",
			"value": "#F2E85C",
			"path": "bpy.data.materials[\"Material\"].node_tree.nodes[\"WaveFormColorRamp\"].color_ramp.elements[2].color"
		}
	]
}

=== DataGeek404/sound-picture/electron-app/src/static/templates/@factory/likely-voyage/template.json
{
	"version": "1.0.1",
	"minBlenderVersion": "3.4.1",
	"allowCompositionNode": false,
	"allowTransparent": false,
	"description": "Energetic Lights",
	"license": "public-domain",
	"parms": [
		{
			"type": "text",
			"title": "Band Name",
			"value": "",
			"path": "bpy.data.objects[\"Band Name\"].modifiers[\"GeometryNodes\"][\"Input_2\"]"
		},
		{
			"type": "text",
			"title": "Song Name",
			"value": "",
			"path": "bpy.data.objects[\"Song Name\"].modifiers[\"GeometryNodes\"][\"Input_2\"]"
		},
		{
			"type": "color",
			"title": "Primary Color",
			"value": "#F2668B",
			"path": "bpy.data.materials[\"Material.001\"].node_tree.nodes[\"Emission\"].inputs[0].default_value"
		},
		{
			"type": "color",
			"title": "Secondary Color",
			"value": "#54A1BF",
			"path": "bpy.data.materials[\"Material.001\"].node_tree.nodes[\"Emission.001\"].inputs[0].default_value"
		},
		{
			"type": "color",
			"title": "Background Color",
			"value": "#261D17",
			"path": "bpy.data.worlds[\"World\"].node_tree.nodes[\"Background\"].inputs[0].default_value"
		},
		{
			"type": "color",
			"title": "Font Color",
			"value": "#D96262",
			"path": "bpy.data.materials[\"FontMaterial\"].node_tree.nodes[\"Emission\"].inputs[0].default_value"
		}
	]
}

=== DataGeek404/sound-picture/electron-app/src/static/templates/@factory/planet-9/template.json
{
  "version": "1.0.0",
  "minBlenderVersion": "3.5.0",
  "allowCompositionNode": true,
  "allowTransparent": false,
  "description": "A scanner drone on a far far away planet ",
  "license": "public-domain",
  "url": "https://github.com/s-a/sonic-sound-picture",
  "parms": [
    {
      "type": "color",
      "title": "Drone Scanner Light Color",
      "value": "#BF6969",
      "path": "bpy.data.lights[\"Spot\"].color"
    },
    {
      "type": "color",
      "title": "Drone Light Color",
      "value": "#8C3A67",
      "path": "bpy.data.materials[\"Drone Light\"].node_tree.nodes[\"Emission\"].inputs[0].default_value"
    },
    {
      "type": "color",
      "title": "Planet 9 Sky Light Color",
      "value": "#11AEBF",
      "path": "bpy.data.materials[\"sunset-473604\"].node_tree.nodes[\"ColorRamp\"].color_ramp.elements[1].color"
    }
  ]
}

=== DataGeek404/sound-picture/electron-app/src/static/templates/@factory/angry-boy/template.json
{
  "version": "1.0.0",
  "minBlenderVersion": "3.4.1",
  "allowCompositionNode": false,
  "allowTransparent": false,
  "description": "The Angry Boy",
  "license": "public-domain",
  "url": "https://github.com/s-a/sonic-sound-picture",
  "parms": [
    {
      "type": "color",
      "title": "Eye Color",
      "value": "#F2935C",
      "path": "bpy.data.materials[\"eyes_material\"].node_tree.nodes[\"ColorRamp\"].color_ramp.elements[2].color",
      "_id": 0,
      "index": 0
    },
    {
      "type": "color",
      "title": "Mouth Color",
      "value": "#1760BF",
      "path": "bpy.data.materials[\"mouth_material\"].node_tree.nodes[\"ColorRamp\"].color_ramp.elements[1].color",
      "_id": 1,
      "index": 1
    }
  ]
}

=== DataGeek404/sound-picture/electron-app/src/static/templates/@factory/afraid-circle/template.json
{
	"version": "1.0.1",
	"minBlenderVersion": "3.4.1",
	"allowCompositionNode": true,
	"allowTransparent": false,
	"description": "Android standing in front of 3 sound reacting bars.",
	"url": "https://github.com/s-a/sonic-sound-picture",
	"license": "public-domain",
	"parms": [
		{
			"type": "color",
			"title": "Sound bar color",
			"value": "#FFFFFF",
			"path": "bpy.data.materials[\"Bands Material\"].node_tree.nodes[\"ColorRamp\"].color_ramp.elements[1].color"
		},
		{
			"type": "color",
			"title": "Android character color",
			"value": "#007DFF",
			"path": "bpy.data.materials[\"Android Material\"].node_tree.nodes[\"Emission\"].inputs[0].default_value"
		}
	]
}

=== DataGeek404/sound-picture/electron-app/src/static/templates/@factory/drones/template.json
{
	"version": "1.0.0",
	"minBlenderVersion": "3.4.1",
	"allowCompositionNode": true,
	"allowTransparent": true,
	"description": "A skybrush inspired drone light show.",
	"license": "public-domain",
	"parms": [
		{
			"type": "color",
			"title": "Meteors",
			"value": "#FFFFFF",
			"path": "bpy.data.materials[\"Meteor\"].node_tree.nodes[\"Emission\"].inputs[0].default_value"
		}
	]
}
